### ISSUE TITLE
template: entity.html:86:63: executing "content" at : error calling history: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by xlidrol** [robertjanetzko/LegendsBrowser2#11]
Hello. There's bunch of problems appears when I'm trying to check more info about civilisations, historical figures, etc, literally everything. 

https://www.upload.ee/files/15298712/xlm_and_xml_plus_files.rar.html
![image](https://github.com/robertjanetzko/LegendsBrowser2/assets/135386667/fb7a58b3-57c5-4738-93bc-c9c55019d3b4)
![image](https://github.com/robertjanetzko/LegendsBrowser2/assets/135386667/fa5784fb-2c09-4e42-9663-04165c78eb2b)

**Comment by robertjanetzko** [comment]
@xlidrol can you reupload the xml files? the archive is only 24 bytes

**Comment by xlidrol** [comment]
@robertjanetzko 
https://www.upload.ee/files/15325109/DW_Legends.rar.html
