### ISSUE TITLE
UNKNWON HistoricalEventChangeHfState and un

### ISSUE THREAD

**Issue by Infiexe** [robertjanetzko/LegendsBrowser2#14]
Load file into the Legends Browser 2: https://mega.nz/file/xthXXTbJ#ysSz7AUfopCKk2s7X8tRFs12qW4COGxbwu77UA-yJ1o
Goto http://localhost:58881/hf/50073, 

Issue 1:
UNKNWON HistoricalEventChangeHfState in numerous entities.

Issue 2:
There's no info who the dwarf was slain by: 
In midsummer of 257, Edem bled to death, slain by in Faithboat

I also have a feature request: It'd be nice to have a column for artifacts objects to quickly see where they're stored. Maybe also a tab for artifacts on sites and governments pages

**Comment by silverwing235** [comment]
Looks like you have a typo in your issue title.

**Comment by daniellovell** [comment]
@silverwing235 
Assuming you're referring to "UNKNWON" that is not a typo by the issue author, its actually written that way.
![image](https://github.com/robertjanetzko/LegendsBrowser2/assets/6250953/6848a080-0dc4-47b0-86f5-a2f7afaeced3)

**Comment by daniellovell** [comment]
Typos in the source:
https://github.com/robertjanetzko/LegendsBrowser2/blob/0d9c02dff6a87bf83d66977293bffa941cf61b15/backend/model/events.go#L540-L541
https://github.com/robertjanetzko/LegendsBrowser2/blob/0d9c02dff6a87bf83d66977293bffa941cf61b15/backend/model/events.go#L145-L146
https://github.com/robertjanetzko/LegendsBrowser2/blob/0d9c02dff6a87bf83d66977293bffa941cf61b15/analyze/df/generate_events.go#L18

**Comment by silverwing235** [comment]
> Typos in the source:
> 
> https://github.com/robertjanetzko/LegendsBrowser2/blob/0d9c02dff6a87bf83d66977293bffa941cf61b15/backend/model/events.go#L540-L541
> 
> https://github.com/robertjanetzko/LegendsBrowser2/blob/0d9c02dff6a87bf83d66977293bffa941cf61b15/backend/model/events.go#L145-L146
> 
> https://github.com/robertjanetzko/LegendsBrowser2/blob/0d9c02dff6a87bf83d66977293bffa941cf61b15/analyze/df/generate_events.go#L18

Ah, well - better go knock on the Bay12Games thread about this, I suppose. Thanks.

**Comment by lethosor** [comment]
This should be pretty straightforward to submit a pull request to fix.

**Comment by Infiexe** [comment]
I don't think it should be labelled as completed. If you reproduce the steps I described in the issue (which wasn't about the type at all), you can see that there are still:

1. Unknown entities, like in the "In early spring of 253, the elf Coce Sharktulip was struck down by Edem with UNKNOWN ARTIFACT in Faithboat" text.
2. Entirely missing information, like in the "In midsummer of 257, Edem bled to death, slain by in Faithboat" text, which doesn't contain the information about who Edem was slain by.

And there's another one that seems unpolished:

3. "In early autumn of 250, the goat Moldath Mirrorreined LINKED TO Edem." - "LINKED TO" seems like a placeholder.
