### ISSUE TITLE
Searching for historic person returns "Not found"

### ISSUE THREAD

**Issue by claudiusmueller** [robertjanetzko/LegendsBrowser2#16]
Searching for a historic person in the search box returns null. See example below:

Searching for "Sabu Lifewoman" returns "Not found":

![df_debug_02](https://github.com/robertjanetzko/LegendsBrowser2/assets/51969417/b222e002-dfdb-4462-a5af-9b2864bd1717)

That person is available via hyperlink when looking elsewhere (historic site in this case):

![df_debug_01](https://github.com/robertjanetzko/LegendsBrowser2/assets/51969417/a44173ea-d755-4587-8cdd-45b1e34962bd)

Clicking that hyperlink takes you to the historic person's information:

![df_debug_03](https://github.com/robertjanetzko/LegendsBrowser2/assets/51969417/a62a4489-bb3c-4ec7-84a1-528fc5c96672)

I'm using version 206 on Firefox in openSUSE 15.5 (if it matters).

**Comment by robertjanetzko** [comment]
Hi, i'm currently unable to reproduce this error. Works for me in both Chrome and Firefox. Could u provide the XML-Files? Perhaps there is an issue with that specific person.

**Comment by robertjanetzko** [comment]
ok, this only happened if you clicked on the highlighted text
