### ISSUE TITLE
Can't open legends_plus.xml

### ISSUE THREAD

**Issue by a-rat-girl** [robertjanetzko/LegendsBrowser2#20]
I cannot get the Legends Browser to recognize the DFHack exported "legends_plus.xml." Renaming it to "legends.xml" allows Legends Broswer to see the xml, but it closes while loading it.

**Comment by RobertDSpencer** [comment]
I'm having the same issue.

**Comment by RobertDSpencer** [comment]
[region3-00100-01-01-legends_plus.zip](https://github.com/user-attachments/files/15842913/region3-00100-01-01-legends_plus.zip)
Here it is.

**Comment by RobertDSpencer** [comment]
I also have the legends file. this is it. They're in the same folder, but only this one shows up
[region3-00100-01-01-legends.zip](https://github.com/user-attachments/files/15861202/region3-00100-01-01-legends.zip)

**Comment by robertjanetzko** [comment]
The files seem to be fine. It as @lethosor said: it always shows only the XML file, but will read the extra information from the plus.xml if it is available. I added an indicator to the loading page that will show if a plus file is available.
