### ISSUE TITLE
Issue with crushed body parts

### ISSUE THREAD

**Issue by RobertDSpencer** [robertjanetzko/LegendsBrowser2#21]
[region3-00100-01-01-legends.zip](https://github.com/user-attachments/files/15794999/region3-00100-01-01-legends.zip)
Seen here, the viewer does not recognize the crushed body part.
<img width="883" alt="Screenshot 2024-06-11 153932" src="https://github.com/robertjanetzko/LegendsBrowser2/assets/28610069/d0abec19-eca1-44b7-81f9-931164033211">

**Comment by robertjanetzko** [comment]
Sorry, but the export currently seems to only export an ID for that body part instead of the name, so there is currently no way to get more details for this event.
