### ISSUE TITLE
Linux Segfault

### ISSUE THREAD

**Issue by Pixead** [robertjanetzko/LegendsBrowser2#7]
Hi, when I try to open my legends.xml file, LegendsBrowser crashes at the very end of the loading. Here's the terminal output :

Loading: /home/pixead/Games/dwarf-fortress/region1-01050-01-01-legends.xml
3.37 GiB / 3.37 GiB [-------------------------------------------------------------------------------------------------------------------------------------------------------------------] 100.00% 140.01 MiB p/s 25s

no legends_plus.xml found

found worldgen params /home/pixead/Games/dwarf-fortress/region1-world_gen_param.txt

found world map /home/pixead/Games/dwarf-fortress/region1-01050-01-01-world_map.bmp
loaded world map imgage as bmp

found world history /home/pixead/Games/dwarf-fortress/region1-01050-01-01-world_history.txt
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x85c499]

goroutine 117 [running]:
github.com/robertjanetzko/LegendsBrowser2/backend/model.(*DfWorld).process(0xc0001ca000)
	/home/runner/work/LegendsBrowser2/LegendsBrowser2/backend/model/process.go:198 +0x18b9
github.com/robertjanetzko/LegendsBrowser2/backend/model.Parse({0xc0002125a0, 0x41}, 0xc0000b6288)
	/home/runner/work/LegendsBrowser2/LegendsBrowser2/backend/model/parse.go:153 +0x5bb
github.com/robertjanetzko/LegendsBrowser2/backend/server.loadWorld(0xc0000d89e0, {0xc0002125a0, 0x41})
	/home/runner/work/LegendsBrowser2/LegendsBrowser2/backend/server/loading.go:119 +0x45
created by github.com/robertjanetzko/LegendsBrowser2/backend/server.loadHandler.ServeHTTP
	/home/runner/work/LegendsBrowser2/LegendsBrowser2/backend/server/loading.go:105 +0x70a

**Comment by robertjanetzko** [comment]
can you zip and upload the xml, so I can have a look at it?

**Comment by Pixead** [comment]
Sure, here it is : https://drive.google.com/file/d/19dBlevP2sCPlD_rJ0Q1Wje_snMhwiPJX/view?usp=sharing

Tell me when you have downloaded it so I can delete it.

Just so you know, I'm a newbie to DF. So maybe I messed up on something. I have just generated this new world however so I don't see what could have gone wrong.

 Opening back DF, Legends mode tells me the XML Dump is incomplete. Maybe the file is corrupted in some way causing the crash?

**Comment by robertjanetzko** [comment]
there was an event type missing in my new version and the debug code to check every that event from the xml file will generate a history entry was still active, so it crashed when it ran into it

the basic XML dump contains only limited data. this is a "feature" of DF. If you want to be able to see all events in a legends viewer try one of the Third-Party DF-Packs that contain dfhack. This tool will allow you to export an additional file with more data.

**Comment by Pixead** [comment]
All right. Thank you very much for the help and the very quick fix! I'm now going to spend a few hours reading the history of this world lol.
